In [2]:
import pandas as pd

df = pd.read_csv('Planilha todas as cidade ESAVI.xlsx - Página1.csv')

print("Tamanho do DataSet (Linhas, Colunas):", df.shape)

Tamanho do DataSet (Linhas, Colunas): (452, 20)

In [5]:
df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,Abadiânia,18.0,2/16/2022,Branca,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
1,Abadiânia,18.0,2/16/2022,Parda,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose / 3: 3ª dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
2,Abadiânia,18.0,2/16/2022,Parda,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: - 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
3,Abadiânia,18.0,2/16/2022,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
4,Abadiânia,18.0,2/16/2022,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 20 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Município de vacinação                              444 non-null    str
 1   Idade Evento                                        444 non-null    float64
 2   Data da Notificação                                 444 non-null    str
 3   Raça/Cor                                            444 non-null    str
 4   Sexo                                                444 non-null    str
 5   Imunobiológico (vacina)                             444 non-null    str
 6   Dose                                                443 non-null    str
 7   Gestante                                            444 non-null    str
 8   Mês de gestação                                     444 non-null    float64
 9   Mulher amamentando no momento da vacinação?         444 non-null    str
 10  Tipo de Evento                                      444 non-null    str
 11  Reação / evento adverso                             438 non-null    str
 12  Classificação de gravidade                          443 non-null    str
 13  Gravidade                                           444 non-null    str
 14  Desfecho (evolução do caso)                         443 non-null    str
 15  Doenças (CID10) - Preexistente                      407 non-null    str
 16  Medicamento em uso anterior ou durante a vacinação  283 non-null    str
 17  Nome do Medicamento                                 444 non-null    str
 18  Houve atendimento médico?                           444 non-null    str
 19  Tipo de Atendimento                                 444 non-null    str
dtypes: float64(2), str(18)
memory usage: 70.8 KB

In [7]:
df.describe()

       Idade Evento  Mês de gestação
count    444.000000       444.000000
mean      36.081081         0.126126
std       21.162762         1.778310
min        0.000000         0.000000
25%       18.000000         0.000000
50%       35.000000         0.000000
75%       51.000000         0.000000
max       90.000000        35.000000

In [8]:
df.dtypes

Município de vacinação                                    str
Idade Evento                                          float64
Data da Notificação                                       str
Raça/Cor                                                  str
Sexo                                                      str
Imunobiológico (vacina)                                   str
Dose                                                      str
Gestante                                                  str
Mês de gestação                                       float64
Mulher amamentando no momento da vacinação?               str
Tipo de Evento                                            str
Reação / evento adverso                                   str
Classificação de gravidade                                str
Gravidade                                                 str
Desfecho (evolução do caso)                               str
Doenças (CID10) - Preexistente                            str
Medicamento em uso anterior ou durante a vacinação        str
Nome do Medicamento                                       str
Houve atendimento médico?                                 str
Tipo de Atendimento                                       str
dtype: object

In [3]:
df['Classificação de gravidade'] = df['Classificação de gravidade'].str.replace(r'^\d+:\s*', '', regex=True)

In [ ]:
df['Data da Notificação'] = pd.to_datetime(df['Data da Notificação'], format='mixed', dayfirst=False)

# Converte a data, para ficar mais padronizado

In [14]:
colunas_remover = ['Gravidade', 'Mês de gestação', 'Mulher amamentando no momento da vacinação?', 'Gestante']
df_limpo = df.drop(columns=colunas_remover)

# Resolvi retirar a coluna 'Gravidade', pois ela se torna redundante, visto que existe a coluna 'Classificação de gravidade'
# Resolvi retirar a coluna 'Mês de gestação' pois quase todas as respostas estão marcadas como 0 ou está vazio
# Resolvi retirar a coluna 'Mulher amamentando no momento da vacinação?' pois apenas existem 3 respostas como 'Sim', o que torna meio irrelevante
# Resolvi retirar a coluna 'Gestante' pois praticamente todas as respsotas estão marcadas como 'Não' ou 0

In [17]:
colunas_para_limpar = [
    'Imunobiológico (vacina)', 'Dose', 'Tipo de Evento', 
    'Reação / evento adverso', 'Classificação de gravidade', 
    'Desfecho (evolução do caso)', 'Tipo de Atendimento'
]

# Remove "Número:" e espaços extras no começo e fim
for col in colunas_para_limpar:
    if col in df_limpo.columns:
        # regex=True permite que o Python entenda o padrão "digito seguido de dois pontos"
        df_limpo[col] = df_limpo[col].astype(str).str.replace(r'\d+:\s*', '', regex=True).str.strip()

In [18]:
df_limpo['Idade Evento'] = df_limpo['Idade Evento'].astype('Int64')

# Converter a idade para inteiro

In [19]:
df_limpo.to_csv('dataset_ESAVI_limpo.csv', index=False, encoding='utf-8-sig')

print("As primeiras 5 linhas do seu novo dataset:")
display(df_limpo.head())

print(f"\nO dataset agora tem {df_limpo.shape[0]} linhas e {df_limpo.shape[1]} colunas.")

As primeiras 5 linhas do seu novo dataset:

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,Abadiânia,18,2022-02-16,Branca,Masculino,Astrazeneca/Fiocruz,1ª Dose,Erro de Imunização,Dose inadequada,Não grave,Cura sem sequelas,0,Não,Não,Não,0
1,Abadiânia,18,2022-02-16,Parda,Masculino,Astrazeneca/Fiocruz,1ª Dose / 2ª Dose / 3ª dose,Erro de Imunização,Dose inadequada,Não grave,Cura sem sequelas,0,Não,Não,Não,0
2,Abadiânia,18,2022-02-16,Parda,Feminino,Astrazeneca/Fiocruz,1ª Dose / - 2ª Dose,Erro de Imunização,Dose inadequada,Não grave,Cura sem sequelas,0,Não,Não,Não,0
3,Abadiânia,18,2022-02-16,Branca,Feminino,Astrazeneca/Fiocruz,1ª Dose / 2ª Dose,Erro de Imunização,Dose inadequada,Não grave,Cura sem sequelas,0,Não,Não,Não,0
4,Abadiânia,18,2022-02-16,Branca,Feminino,Astrazeneca/Fiocruz,1ª Dose,Erro de Imunização,Dose inadequada,Não grave,Cura sem sequelas,0,Não,Não,Não,0

O dataset agora tem 452 linhas e 16 colunas.